✨ return both stdout & stderr

diff --git a/bash/functions/fail b/bash/functions/fail
--- a/bash/functions/fail
+++ b/bash/functions/fail
@@ -1,8 +1,10 @@
 #!/bin/bash
 function main() {
+  echo "output:"
   echo
-  echo " (╯°□°）╯︵ $(echo "$1" | flip 2>/dev/null)" >&2
+  echo " (╯°□°）╯︵ $(echo "$1" | flip 2>/dev/null)"
   echo
+  echo "error: $1" >&2
   exit ${2-1}
 }
 main "$@"
