fix issue -m option has unexpect previuos messages
  - http://blog.outsider.ne.kr/972

diff --git a/git_template/hooks/prepare-commit-msg b/git_template/hooks/prepare-commit-msg
--- a/git_template/hooks/prepare-commit-msg
+++ b/git_template/hooks/prepare-commit-msg
@@ -1,11 +1,49 @@
 #!/bin/sh
+#
+# An example hook script to prepare the commit log message.
+# Called by "git commit" with the name of the file that has the
+# commit message, followed by the description of the commit
+# message's source.  The hook's purpose is to edit the commit
+# message file.  If the hook fails with a non-zero status,
+# the commit is aborted.
+#
+# To enable this hook, rename this file to "prepare-commit-msg".
 
-BRANCH_NAME=$(git branch | grep '*' | sed 's/* //')
-if [ $BRANCH_NAME != '(no branch)' ]
-then
-  echo "#"
-  echo "# Last 5 commit messages" >> $1
-  echo "# ----------------------" >> $1
-  COMMITS=`git log --pretty=format:"# %h %s [%an]" -5`
-  echo "${COMMITS}" >> $1
-fi
+# This hook includes three examples.  The first comments out the
+# "Conflicts:" part of a merge commit.
+#
+# The second includes the output of "git diff --name-status -r"
+# into the message, just before the "git status" output.  It is
+# commented because it doesn't cope with --amend or with squashed
+# commits.
+#
+# The third example adds a Signed-off-by line to the message, that can
+# still be edited.  This is rarely a good idea.
+
+case "$2,$3" in
+# merge,) ;;
+#   /usr/bin/perl -i.bak -ne 's/^/# /, s/^# #/#/ if /^Conflicts/ .. /#/; print' "$1" ;;
+
+ ,|template,)
+    BRANCH_NAME=$(git branch | grep '*' | sed 's/* //')
+    if [[ $BRANCH_NAME != '(no branch)' ]]
+    then
+      HASLOG=$(git log 2>&1)
+      if [[ "$HASLOG" != *fatal* ]]; then
+        echo "#" >> $1
+        echo "# Last 5 commit messages" >> $1
+        echo "# ----------------------" >> $1
+        COMMITS=`git log --pretty=format:"# %h %s [%an]" -5`
+        echo "${COMMITS}" >> $1
+      fi
+    fi
+   ;;
+#   /usr/bin/perl -i.bak -pe '
+#      print "\n" . `git diff --cached --name-status -r`
+#  if /^#/ && $first++ == 0' "$1" ;;
+
+  *) ;;
+esac
+
+# SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
+# grep -qs "^$SOB" "$1" || echo "$SOB" >> "$1"
